name: Publish Container Image
on:
  push:
    tags: [ 'v*' ]

jobs:
  publish-container:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set version number
        run: |
          echo "VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
          echo "DOCKER_REPOSITORY=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: version=${{ env.VERSION }}
          tags: |
            ghcr.io/${{ env.DOCKER_REPOSITORY }}:latest
            ghcr.io/${{ env.DOCKER_REPOSITORY }}:${{ env.VERSION }}
          cache-from: type=registry,ref=ghcr.io/${{ env.DOCKER_REPOSITORY }}:latest
          cache-to: type=inline